nyc_data/ppe/aggregations.py, nyc_data/ppe/static/style.css
My deep and sincere apologies to CSS.
=> Add balance graph

nyc_data/ppe/static/script.js, nyc_data/ppe/static/style.css, nyc_data/ppe/templates/base.html, nyc_data/ppe/templates/dashboard.html
=> Implement dashboard rollup toggle

nyc_data/ppe/aggregations.py
=> Hide the donate column in the table

nyc_data/ppe/aggregations.py, nyc_data/ppe/static/style.css, nyc_data/ppe/templates/base.html, nyc_data/ppe/templates/dashboard.html
=> Footer with definitions, tooltips for column headers

nyc_data/ppe/aggregations.py
=> Correcting balance percentages

nyc_data/ppe/templates/dashboard.html, nyc_data/ppe/views.py
=> Make mayoral rollup the default

nyc_data/ppe/aggregations.py, nyc_data/ppe/tests.py
Fixed incorrect range() param (turns out that range(6) only returns numbers 0 1 2 3 4 5...). Changed it to range(7) so we get hospitalization data for a complete week.
Fixed related test function using projection.
=> Projection Fix

nyc_data/ppe/templates/verify_upload.html, nyc_data/ppe/views.py, nyc_data/xlsx_utils.py
Handles file formats and types not expected by the mapper. 
Styling is not good, but wanted to get functionality into a PR asap
=> throw error when unrecognized file format/type

nyc_data/ppe/aggregations.py, nyc_data/ppe/data_import.py, nyc_data/ppe/data_mapping/mappers/hospital_deliveries.py, nyc_data/ppe/drilldown.py, nyc_data/ppe/templates/dashboard.html, nyc_data/ppe/templates/drilldown.html, nyc_data/ppe/templatetags/ppe_extras.py, nyc_data/ppe/views.py, nyc_data/xlsx_utils.py
Lots o' stuff:
- use bulk import so we can import deliveries without taking forever
- use delivery-based demand proxy w/ Peng's IMHE model
- num-to-str cleanups (fixes #38 )
- drilldown page will show inventory
=> Assorted Fixes

nyc_data/ppe/aggregations.py, nyc_data/ppe/templates/dashboard.html
Made a variable for the demand projection tooltip display.
=> Tooltip Message Update

nyc_data/ppe/static/style.css, nyc_data/ppe/templates/base.html, nyc_data/ppe/templates/dashboard.html, nyc_data/ppe/templates/drilldown.html
=> Drilldown tables

nyc_data/ppe/data_mapping/utils.py, nyc_data/ppe/views.py
```
Parsed request as 2020-04-15->2020-05-14
Unknown date format: 123
[15/Apr/2020 13:55:14] "GET /?start_date=123 HTTP/1.1" 200 19562
```
=> Log date parsing metadata

nyc_data/ppe/aggregations.py, nyc_data/ppe/templates/base.html
=> Copy edits

nyc_data/ppe/aggregations.py, nyc_data/ppe/static/style.css, nyc_data/ppe/templates/base.html, nyc_data/ppe/views.py
=> Drilldown dashboard totals

nyc_data/nyc_data/settings/prod.py, nyc_data/ppe/data_mapping/mappers/donations.py, nyc_data/ppe/data_mapping/utils.py
The newest spreadsheet used a two-digit year, so I added a pattern for that. Also, the comments field in one row was coming across as null, so I forced that hand a bit – but not sure why it was happening for this row and not others.
=> Fix donations upload

Pipfile, Pipfile.lock, nyc_data/nyc_data/auth.py, nyc_data/nyc_data/settings/common.py, nyc_data/nyc_data/urls.py, nyc_data/ppe/static/style.css, nyc_data/ppe/templates/base.html, nyc_data/ppe/tests.py, nyc_data/ppe/views.py, nyc_data/templates/account/login.html, nyc_data/templates/account/logout.html, nyc_data/templates/account/password_change.html, nyc_data/templates/account/password_reset.html, nyc_data/templates/account/password_reset_done.html, nyc_data/templates/account/password_reset_from_key.html, nyc_data/templates/account/password_reset_from_key_done.html, nyc_data/templates/account/signup_closed.html
Implements django-allauth for basic authentication, prohibiting self-registration.
Email is not configured at this point, so password resets will not yet really work.
=> WIP: Authentication

nyc_data/nyc_data/auth.py, nyc_data/nyc_data/settings/common.py, nyc_data/nyc_data/settings/prod.py, nyc_data/nyc_data/urls.py, nyc_data/ppe/aggregations.py, nyc_data/ppe/data_import.py, nyc_data/ppe/data_mapping/mappers/dcas_sourcing.py, nyc_data/ppe/data_mapping/mappers/dcas_vents.py, nyc_data/ppe/data_mapping/mappers/donations.py, nyc_data/ppe/data_mapping/utils.py, nyc_data/ppe/drilldown.py, nyc_data/ppe/migrations/0017_auto_20200416_2258.py, nyc_data/ppe/migrations/0017_dataimport_current_as_of.py, nyc_data/ppe/migrations/0018_merge_20200417_0336.py, nyc_data/ppe/migrations/0019_purchase_donation_date.py, nyc_data/ppe/models.py, nyc_data/ppe/tests.py, nyc_data/ppe/views.py, nyc_data/xlsx_utils.py
1 line change & a run of the autoformatter
=> Flat demand

nyc_data/ppe/dataclasses.py
=> Revise nomenclature

nyc_data/ppe/data_mapping/mappers/dcas_sourcing.py, nyc_data/ppe/data_mapping/utils.py
cc @mjacksonw 
1. merge and deploy
2. go to admin view
3. click "retry" on the failed upload
4. ????
5 . Non-profit?
=> Handle null bools properly

nyc_data/ppe/admin.py
This will also allow remove imports & and sorts of QA / changes by modifying that "status" field (at your own risk!)
=> Add data imports to the admin view

nyc_data/nyc_data/auth.py, nyc_data/nyc_data/settings/common.py, nyc_data/ppe/admin.py, nyc_data/ppe/aggregations.py, nyc_data/ppe/data_mapping/mappers/dcas_make.py, nyc_data/ppe/data_mapping/mappers/dcas_sourcing.py, nyc_data/ppe/data_mapping/mappers/dcas_vents.py, nyc_data/ppe/data_mapping/utils.py, nyc_data/ppe/models.py, nyc_data/ppe/templates/week_breakdown.html, nyc_data/ppe/urls.py, nyc_data/ppe/views.py, nyc_data/xlsx_utils.py
See the first commit for details & places to tweak
=> Very basic and rough rollups available on `/byweek`

docker-compose.yml, nyc_data/xlsx_utils.py
Profiling revealed that the way we were reading from the spreadsheets was really slow. Optimize to use the row iterator & load the spreadsheets in read_only mode
=> Optimize xlsx_reader usage
